macmillanpublishers/bookmaker

core/pdfmaker/pdfmaker.rb
Escape chars (\) were getting dropped when the CSS was embedded in the docraptor HTML. Fixed.
=> Preserving CSS escape characters

config.rb, core/coverchecker/coverchecker.rb, core/epubmaker/epubmaker.rb, core/filearchive/filearchive.rb, core/header.rb, core/imagechecker/imagechecker.rb, core/metadata.rb, core/tmparchive/tmparchive.rb
Users can now either define a directory for submitting project assets as well as a directory for storing finished conversions, or bookmaker will just look in the same folder where the input file was submitted, and store the finished stuff there.
=> Updating required folder structure

core/stylesheets/stylesheets.rb
If a full path to a CSS file is not provided in config.json, bookmaker will assume the value in the json is a filename and will look for that css filename in the assets dir.
=> Looking for CSS in assets dir if no path is provided

README.md, core/epubmaker/epubmaker.rb
epubmaker can now run even if no front cover is included.
=> Removing cover dependency

core/imagechecker/imagechecker.rb
If cover file is also a regular img in the book, imagechecker will preserve it.
=> Checking to see if cover file is img

core/htmlmaker/wordtohtml.xsl
In htmlmaker XSL, adding handling to evaluate text nodes in place, rather than re-ordering them.
=> Adding better handling for text nodes

core/htmlmaker/wordtohtml.xsl
When Word symbol encoding is used, convert correctly
=> fixing copyright symbol

core/metadata.rb, core/pdfmaker/pdfmaker.rb
Users can include separate title page images for POD and EPUB, specifying filenames in the project JSON.
=> Adding support for titlepage images

core/coverchecker/coverchecker.rb, core/imagechecker/imagechecker.rb
If images are not submitted, bookmaker will check for previous existing versions of images and covers and pick those up for current conversions
=> Fallback to use previous images if no new images submitted

core/stylesheets/stylesheets.rb
CSS imports are now supported. If a printcss or epubcss references an import, bookmaker will source that in first, and then add the standard CSS and finally any oneoff CSS. Only supports locally-hosted CSS (e.g., can't resolve weblinks currently).
=> Adding support for CSS imports

core/htmlmaker/evaluate_pis.js, core/htmlmaker/htmlmaker.rb
Adding support for in-text processing instructions. Paragraphs tagged as "Bookmaker Processing Instruction (bpi)" will have the text processed as defined in https://github.com/macmillanpublishers/bookmaker/tree/master/core/htmlmaker/evaluate_pis.js and then those paragraphs will be removed.
=> Adding processing instruction support

core/epubmaker/epubmaker.rb, core/header.rb
Revising so that an image is only copied into an epub file if it is actually referenced in the file or used in an addon
=> Revising handling for addon images

core/htmlmaker/htmlmaker.rb, core/htmlmaker/lists.js, core/htmlmaker/wordtohtml.xsl
Adding handling to convert child element lists (e.g., within extract, sidebar, etc) as real lists.
=> Adding support for lists

core/filearchive/filearchive.rb
In filearchive.rb, instead of just checking to see if the main final archive dir exists, check to see if each subdir exists and create them one by one.
=> Creating final dirs one by one

core/header.rb
This is a companion to Pull Request #78 in the addons repo:
https://github.com/macmillanpublishers/bookmaker_addons/pull/78
I needed open3 to capture stderr from the epubcheck.jar command (to test for errors).
I searched all bookmaker files on my Mac, it looks like the epub_postprocessing.rb is the only script calling the runjar method.
=> Epubcheck alert

core/header.rb
Really a cosmetic change to go with the python dropbox-api, so the run_python method is pointedly accepting multiple arguments.  Tested as part of Bookmaker_addons PR 106, passed tests.
=> editing runpython method in bkmkr::tools to take many argments

core/htmlmaker/inlines.js
Per our standard handling for design notes, we will remove all inline design notes when converting to HTML.
Tested on staging.
@mattretzer or @ericawarren can you review and approve?
=> Removing inline design notes

core/cleanup/cleanup.rb, core/coverchecker/coverchecker.rb, core/epubmaker/epubmaker.rb, core/filearchive/filearchive.rb, core/header.rb, core/htmlmaker/htmlmaker.rb, core/imagechecker/imagechecker.rb, core/pdfmaker/pdfmaker.rb, core/stylesheets/stylesheets.rb, core/tmparchive/tmparchive.rb
All of this is pretty straightforward except for stuff in header.rb & epubmaker.rb:
- In the header, I added a provision to the jsonlog method so when invoked from tmparchive.rb it will clear old contents of the jsonlog hash
- Epubmaker's call to the processxsl method in the header was logging to the old logfile. I tried logging to the stderr-out.txt file instead, but the deploy.bat is using the file already so ruby can't open it.  I settled for keeping the parameter in the method itself but passing it an empty string from epubmaker, and removing the output redirect from the shell commands in the header...  so now the output from xsl transformations end up in the stderr-out.txt file anyways.
=> Remove old logging from bookmaker repo

core/header.rb
Adding config values to the pdfmaker prince command, so it works on both mac and windows. Tested locally and on staging.
=> Adjusting prince command for windows

core/htmlmaker/bandaid.js
With the current XSL conversion, figure elements occasionally duplicate the id of a previous sibling or parent. Adding a little patch to force fig ids to be unique. I expect this will be fixed for real in the htmlmaker_js.
@mattretzer can you review?
=> Adding handling for figs duplicating ids

core/htmlmaker/htmlmaker.rb, core/htmlmaker/version_metatag.js, core/htmlmaker/xsl_only.js
Hi @nelliemckesson ,  this PR, together with its [companion PR in addons](https://github.com/macmillanpublishers/bookmaker_addons/pull/158), include:
- the template version check, 
- edits to htmlmaker.rb so it chooses js or xsl conversion based on the template_version
- and some of the old js code, consolidated & re-added, to support the xsl conversion.
One comment/question:
In htmlmakerpreprocessing.rb I am writing the template_version-string to the config.json file.
htmlmaker.rb then scoops up this value from the config.json file and writes it into the html as a meta element.
However when metadatapreprocessing.rb runs, it overwrites the existing config.json, so that value is no longer in config.json.  It doesn’t matter functionally; I could also re-write the value in …
=> Templateversion

core/htmlmaker/headings.js
@nelliemckesson , please review:
This is a fix for https://github.com/macmillanpublishers/bookmaker_assets/issues/61
As we discussed, & pretty straightforward :)  Tested with known problem files, looked good.
=> change auto-added heading class from nonprinting to chaptitlenonprinting

core/header.rb
This is a small change to the bookmaker production environment:
It archives log.jsons for bookmaker runs instead of overwriting them.
@lsquill , please review?
=> archive existing json_log instead of overwrite

core/cleanup/cleanup.rb, core/coverchecker/coverchecker.rb, core/epubmaker/epubmaker.rb, core/filearchive/filearchive.rb, core/header.rb, core/imagechecker/imagechecker.rb, core/metadata.rb, core/pdfmaker/pdfmaker.rb, core/stylesheets/stylesheets.rb, core/tmparchive/tmparchive.rb
1 of a set of 5 PR's to handle concurrent bookmaker runs, both with the tmpdir & the done_dir.
Straightforward unless a 'locked' done dir for the exact same ISBN exists, then it retries every minute for 15 minutes, then spawns a new done_dir with an error.txt in the root.
Repos affected:
bookmaker
bookmaker_addons (https://github.com/macmillanpublishers/bookmaker_addons/pull/203)
bookmaker_connectors
pitstop_watch
covermaker
=> Singlerun lock
