macmillanpublishers/bookmaker

config.rb
header.rb

Users can now configure key bookmaker paths in config.rb

Adding separate config file

---

metadata.rb

Project metadata will now be read from a user-supplied JSON file

Adding support for project-level config files

---

metadata.rb

Paths to CSS files are now provided by the user via config.json, and passed to variables in metadata.rb

Adding CSS paths to metadata

---

core/pdfmaker/css/torDOTcom/pdf.css
core/pdfmaker/pdfmaker.rb
core/stylesheets/stylesheets.rb

Adding stylesheet customizations to the macmillan-specific postprocessing file in bookmaker_addons.

Pulling out stylesheet customizations

---

config.rb
core/header.rb
core/pdfmaker/pdfmaker.rb

You can now configure your PDF processor in config.rb, and bookmaker will run the correct process accordingly

Adding method to call PDF processor

---

config.rb
core/epubmaker/epubmaker.rb
core/header.rb
core/htmlmaker/htmlmaker.rb
core/pdfmaker/pdfmaker.rb

Users can configure their saxon version in config.rb. (Also fixed some pdfmaker bugs I introduced in the last pull.)

Users can configure saxon version

---

README.md
config.rb
core/header.rb
core/htmlmaker/docxtoxml.py
core/htmlmaker/htmlmaker.rb

Removing powershell/Word dependency, replacing with Python 2.7.x

Replacing PowerShell with Python

---

core/cleanup/cleanup.rb
core/tmparchive/tmparchive.rb

tmparchive was trying to pickup some hidden system files that was causing failure. Reworked it to ignore those files.

Fixing image handling to ignore system files

---

core/epubmaker/epubmaker.rb
core/epubmaker/zipepub.py
core/header.rb

SORRY @mattretzer :crying_cat_face:

Replacing zip with python

---

config.rb
core/epubmaker/epubmaker.rb
core/header.rb

HTMLBook xsl can only run with saxon9pe, I believe, so adding a contingency plan.

Adding custom xslproc command

---

core/header.rb

Add a line to log a message when a section is moved via Bkmkr::Tools.movesection

Adding log message to section mover

---

config.rb
core/header.rb
core/tmparchive/tmparchive.rb

Fixing filename space issue

---

core/cleanup/cleanup.rb
core/coverchecker/coverchecker.rb
core/epubmaker/epubmaker.rb
core/filearchive/filearchive.rb
core/htmlmaker/htmlmaker.rb
core/imagechecker/imagechecker.rb
core/pdfmaker/pdfmaker.rb
core/stylesheets/stylesheets.rb
core/tmparchive/tmparchive.rb

Revising log messages

---

README.md
core/stylesheets/stylesheets.rb

CSS oneoff stylesheets can now be added per project. See README.md.

Adding support for CSS oneoffs

---

config.rb
core/cleanup/cleanup.rb
core/header.rb
core/metadata.rb

Revising cleanup ftp handling and methodizing certain actions

Refactoring cleanup

---

core/cleanup/cleanup.rb
core/coverchecker/coverchecker.rb
core/epubmaker/epubmaker.rb
core/filearchive/filearchive.rb
core/header.rb
core/htmlmaker/htmlmaker.rb
core/imagechecker/imagechecker.rb
core/metadata.rb
core/pdfmaker/pdfmaker.rb
core/stylesheets/stylesheets.rb
core/tmparchive/tmparchive.rb
core/utilities/mcmlln-tools.rb

A compete refactor of all the core code to pull processes into methods, and to centralize shared utilities.

Refactoring to add methods

---

core/epubmaker/epubmaker.rb
core/htmlmaker/evaluate_pis.js
core/utilities/mcmlln-tools.rb

Adding processing instructions to override book metadata.

Updating metadata handling and adding metadata PI

---

core/epubmaker/epubmaker.rb
core/imagechecker/imagechecker.rb

Adding a check to convert images to supported file formats.

Checking image types and converting

---

core/htmlmaker/evaluate_pis.js
core/htmlmaker/headings.xsl
core/htmlmaker/wordtohtml.xsl
core/utilities/movesection.js

Adding new processing instructions to insert custom CSS styles for paragraphs and to add a link around a paragraph.
Also adjusted logic for moving sections around, for the epub.

Adding new PIs and fixing content reorg

---

config.rb

Logs will now be stored in dropbox/bookmaker_logs

Updating log dir

---

core/header.rb

Drop only the true file extension for 'filename' variable in header (split at the last period)

Infile name

---

core/htmlmaker/wordtohtml.xsl

Adds conversion support for the new FM and BM nonprinting header styles

adding support for other nonprinting header styles

---

core/htmlmaker/inlines.js

@mattretzer Matt can you review and approve if it looks ok?

Support for inline images

---

core/htmlmaker/strip-toc.js

Better handling for detecting a user-submitted TOC and tagging it accordingly. 
Fixes https://github.com/macmillanpublishers/bookmaker_addons/issues/102
@mattretzer @ericawarren Matt or Erica, can you review and approve?

Adding more robust texttoc handling

---

core/htmlmaker/evaluate_pis.js
core/imagechecker/imagechecker.rb

Processes custom space break images added by users via processing instructions, and converts to figure tags.
Also fixed a typo in imagechecker.
@mattretzer Matt can you review and approve?

Adding support for custom space break images

---

core/htmlmaker/wordtohtml.xsl

Adding:
Chapt Title ALT (act) -- will trigger new top-level section
BM Head ALT (abmh) -- will trigger new top-level section
FM Head ALT (afmh) -- will trigger new top-level section
Space Break - Internal (int) -- allowed inside other blocks (like extracts)
@ericawarren or @mattretzer can you review and approve if it looks ok?

Styles1123

---

core/coverchecker/coverchecker.rb

Tested on staging with the test MS, I will merge in the other PR's for bookmaker & run it through the full test process on Tuesday prior to merge/deployment (and resubmit for review if any issue)
But @nelliemckesson or @ericawarren  can you go ahead and review (b/c its just one line/command)?

adding 5 second pause before moving pdf in coverchecker

---

core/htmlmaker/bandaid.js
core/htmlmaker/htmlmaker.rb
core/htmlmaker/wordtohtml.xsl

Accidentally added an ambiguous xsl rule, so I fixed it.
@mattretzer Matt can you review and approve?

Fixing ambiguous XSL rule

---

README.md
core/cleanup/cleanup.rb
core/coverchecker/coverchecker.rb
core/epubmaker/epubmaker.rb
core/filearchive/filearchive.rb
core/header.rb
core/htmlmaker/htmlmaker.rb
core/imagechecker/imagechecker.rb
core/metadata.rb
core/pdfmaker/pdfmaker.rb
core/stylesheets/stylesheets.rb
core/tmparchive/tmparchive.rb
core/utilities/mcmlln-tools.rb

@nelliemckesson :  I have finished my first daft of adding json-logging for bookmaker_core scripts.  I'm just submitting a PR in case you have time and want to briefly look at some of it before we meet, but I imaging we'll go over it in some detail this afternoon, + I have some questions regardless:)

Json logging for bookmaker_core

---

core/htmlmaker/bandaid.js
core/htmlmaker/wordtohtml.xsl

Adding processing instructions to the set of paragraphs that should be included inside blockquotes, pres, asides, etc., if they are found.
@ericawarren can you take a stab at reviewing?

Adding PIs to versatile conversion paras

---

.travis.yml

Forgot to change this, I think it's why Travis didn't run on my PR a moment ago
Either of you can review plz!

have to add 'master' to branch whitelist to enable tests

---

core/htmlmaker/bandaid.js

Removing or replacing brackets in image sources and urls

---

core/htmlmaker/htmlmaker.rb

this has a companion PR in addons, with the same branch name, to be added momentarily.
For now I just commented out the xsl bits, but I can delete them if that's preferable?
@nelliemckesson, please review?

replacing xsl transformation to html with htmlmaker_js

---

core/htmlmaker/headings.js

Hi @nelliemckesson , I think this does what we talked about in terms of revised heading handling for section starts..  I mean, it works :)
Please review?

Ss headings

---

core/htmlmaker/htmlmaker.rb

This is another PR spanning 2 repos, this is part 1 of 2.
Removing most version checking (that's getting moved to addons) and conditional bookmaker conversions from bookmaker repo. 
@lsquill , please review?

Versionerr

---

core/htmlmaker/htmlmaker.rb

a little cleanup, companion to: https://github.com/macmillanpublishers/bookmaker_addons/pull/186
Please review @lsquill

really just a little cleanup

---

config.rb
core/header.rb
core/pdfmaker/pdfmaker.rb

Part one of 4 PR's for running Prince locally instead of DocRaptor.
@lsquill , please review.

Localprince

---

core/htmlmaker/bandaid.js

Resolves all erroring manuscripts from  https://github.com/macmillanpublishers/bookmaker/issues/201
Tested, looks good.
@lsquill , please review!

patch for emty nav item/hyperlink bug

---

core/htmlmaker/wordtohtml.xsl

To repair https://github.com/macmillanpublishers/bookmaker/issues/204.
Tested on document where issue presented, tested via dev_testing protocol as well & diff'd demo output.

Xslpatch epigraph

---

config.rb
core/header.rb
core/htmlmaker/htmlmaker.rb
core/htmlmaker/wordtohtml.xsl
core/pdfmaker/pdfmaker.rb

merging upstream updates from master into sectionstartstaging branch.
Some are necessary (rm external dependencies) others are moot (xsl updates) but easier to do all at once,

Sss mergefrommaster

---

core/htmlmaker/wordtohtml.xsl

to fix new bug : https://github.com/macmillanpublishers/bookmaker/issues/208
Tested this patch with offending document, the doc that created need for the first patch, and full diff/test procedure.

patching recent patch in xsl-left consecutive bpi's in trouble

---

core/header.rb
core/utilities/evaltemplates.js

Pt 1 of 2 here:
https://github.com/macmillanpublishers/bookmaker_addons/pull/195
eval templates is for updating info in addon templates for epub; adding extra parameter to pass in the one hardcoded style instead of adding conditionals here and hardcoding more stylenames.

preparing bookmaker toolchain for making epubs with rsuite styled documents pt 2 of 2

---

core/htmlmaker/version_metatag.js
core/tmparchive/tmparchive.rb

bug discovery & repair in conjunction with development of branch of the same name in bookmaker_addons repo.

Inputconfigbug

---

config.rb
core/header.rb

there will be a companion pr in covermaker repo

allowing different prince cmds based on presence of http-auth in cfg.rb
